SecondMVCFile/Models/Book.cs
namespace SecondMVCFile.Models
{
    public class Book
    {
        public int BookID { set; get; }
        public String Title { set; get; }
        public float Cost { set; get; }
        public String AuthorName { set; get; }
    }
}

SecondMVCFile/Models/ErrorViewModel.cs
namespace SecondMVCFile.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SecondMVCFile/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondMVCFile.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public int Add(int x, int y) 
        { 
        return x + y;
        }
    }
}

SecondMVCFile/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SecondMVCFile.Models;
using System.Diagnostics;
using System.Text;

namespace SecondMVCFile.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;
        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _configuration = configuration;
            _logger = logger;
        }
        public IActionResult Menu()
        {
            String conString = _configuration.GetConnectionString("DefaultConnection");
            _logger.Log(LogLevel.Information,conString);
            return View();
        }
        public ActionResult Echo(String name, String city)
        {
            String s1="user "+ name +" from city"+ city ;
            ViewData.Add("Data1", s1);
            return View();
        }
        public ActionResult SayHello(String name)
        {
            String s1 = ("Hello "+ name );
            ViewData.Add("Data1", s1);
            return View("Echo");
        }


        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(int x, IFormCollection collection)
        {
            StringBuilder data = new StringBuilder(500);
            data.Append("x:");
            data.Append(x);
            data.Append("   ");
            data.Append("name:");
            data.Append(collection["name"]);
            data.Append("   ");
            data.Append("password:");
            data.Append(collection["password"]);

            //foreach (var item in collection)
            //{
            //    data.Append(item.Key);
            //    data.Append(":");
            //    data.Append(item.Value);
            //    data.Append(" ");
            //}
            ViewData["x"] = data.ToString();
            return View("IndexPost");
        }
        public ActionResult DoTask(int? id)
        {
            if(id.HasValue)
            {
                ViewData["id"] = id.Value;
            }
            else { ViewData["id"] = 0;}
            return View();
        }
        // redirect to action
        public ActionResult Test()
        {

            return RedirectToAction("Index");
        }
        //passing an obj to viewdata
        public IActionResult GetBook()
        {
            Book b1 = new Book() { AuthorName = "H Lee" };
            ViewData["book"] = b1;
            return View();
        }
        [ResponseCache(Duration =15)]
        public IActionResult GetTime()
        {
            String todate = DateTime.Now.ToLongTimeString();
            ViewData["date"] = todate;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SecondMVCFile/Controllers/NewController.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondMVCFile.Controllers
{
    public class NewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Start()
        {
            return View();
        }
    }
}

SecondMVCFile/Controllers/PartialViewController.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondMVCFile.Controllers
{
    public class PartialViewController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Tabs()
        {
            ViewData["data1"] = "Tom and jerry are Good Friends";
            return View();
        }
    }
}

SecondMVCFile/Views/PartialView/ChildList.cshtml
<div style="background-color:cyan">
    <hr/>
<h1> From Child View</h1>
<ul>
    <li>Benz</li>
    <li> Innova</li>
    <li> Tesla M3</li>
</ul>

</div>

SecondMVCFile/Views/PartialView/ChildViewData.cshtml
<div style="background-color: pink">
    <h1>From ChildViewData View:@ViewData["data1"]</h1>
</div>

SecondMVCFile/Views/PartialView/Index.cshtml
<h1>INDEX</h1>
@{
    var all_route_parms = new Dictionary<string, string>
    {
    {"x","200"},{"y","50"}
    };
}
<!--razor helper-->
<div>
    <a asp-action="Add" asp-controller="Calculator"
    asp_route-x="258" asp-route-y="6">CallAdd asp-route</a>
</div>
<div>
    <a asp-action="Add" asp-controller="Calculator"
       asp-all-route-data="all_route_parms"> CallAdd all_route_parms</a>
</div>
@await Html.PartialAsync("ChildList")

SecondMVCFile/Views/PartialView/MyView.cshtml
<hr/>
<h1> Andhaman Beaches List</h1>
<ul>
    <li> RadhaNagar</li>
    <li>Neal Island</li>
    <li>Ross Island</li>
    <li>Wandoor</li>
</ul>
<hr/>

SecondMVCFile/Views/PartialView/Score.cshtml
<div class="text-center">
    <h1>Score</h1>
    <h3>256 for 4 in 20 overs</h3>
</div>

SecondMVCFile/Views/PartialView/Tabs.cshtml
@{
    ViewData["Title"] = "Tabs Page";
}

<div>
    <!--Tab Buttons-->
    <ul id="tabstrip" class="nav nav-tabs" role="tablist">
        <li class="active">
            <a href="#_FirstTab" role="tab" data-toggle="tab">Submission</a>|
        </li>
        <li>
            <a href="#_SecondTab" role="tab" data-toggle="tab">Search</a>|
        </li>
        <li>
            <a href="#_ThirdTab" role="tab" data-toggle="tab">Comments</a>|
        </li>
    </ul>

  <!--Tab Content Containers-->
   
  <div class="tab-content">
    <div class="tab-pane fade in active" id="_FirstTab">
            <partial name="Score" />
            <div class="tab-pane fade" id="_SecondTab">
                <partial name="Childlist"/>
            </div>
            <div class="tab-pane fade" id="_ThirdTab">
                <partial name="ChildViewdata" view-data="ViewData"/>
              </div>      
    </div>
</div>
</div>
<hr/>
<partial name="Score" />
<partial name="Childlist" />
<partial name="ChildViewdata" view-data="ViewData" />

SecondMVCFile/Views/Shared/_BooksList.cshtml
@{
    ViewData["Title"] = "_BooksList";
}

<hr />
<h1>From Books List</h1>
<ul>
    <li> Wasted in Engineering</li>
    <li> It happen for a Reason</li>
    <li> The Leader in you</li>
    <li> The one Minute Manager</li>
</ul>

SecondMVCFile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SecondMVCFile</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SecondMVCFile.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SecondMVCFile</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SecondMVCFile - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SecondMVCFile/Views/Shared/_MovieList.cshtml
@{
    ViewData["Title"] = "_MovieList";
}
<hr/>
<h1>From Movie List</h1>
<ul>
    <li> SpiderMan</li>
    <li> SuperMan</li>
    <li> BatMan</li>

</ul>